Scalability blocks
foundation-model-stack/fms-dgt pull request #142
Opened 2024-10-24 17:55 UTC by mvcrouse

## Related Issue
Supports #ISSUE_NUMBER

## Related PRs
This PR is not dependent on any other PR

## What this PR does / why we need it

## Special notes for your reviewer

## If applicable**
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-10-25 15:44 UTC, kpfadnis requested changes
Left minor comments. Overall looks good.

2024-10-25 20:36 UTC, mvcrouse commented on fms_dgt/base/multiprocessing.py
> +        partition_size = len(inputs) // len(self._workers)
Yep good call, just fixed

2024-10-28 13:50 UTC, kpfadnis approved these changes
Looks good to me. 

@sivasankalpp had some reservations about worker management in `TENSOR PARALLEL` settings.

2024-10-28 13:50 UTC, kpfadnis commented on fms_dgt/base/multiprocessing.py
> +                continue
Isn't it better to just `break` out of the loop at this point where there are no more inputs to pass on to a worker?

2024-10-28 13:50 UTC, kpfadnis commented on fms_dgt/base/multiprocessing.py
> +        for i in range(len(self._workers)):
For readability purposes, can we say

```python
for worker_idx in range(len(self._workers)):
```

2024-10-29 19:23 UTC, merged