Block design
foundation-model-stack/fms-dgt pull request #24
Opened 2024-07-09 19:12 UTC by mvcrouse

## What this PR does / why we need it

Abstracts generators / validators to share a common parent class. Now they are all called the same way and can be specified with shared configs

## Special notes for your reviewer

## If applicable**
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

2024-07-09 20:37 UTC, drugilsberg approved these changes
Lgtm, should generalize a lot the framework

2024-07-09 21:02 UTC, sivasankalpp approved these changes
LGTM, nice work!

2024-07-10 13:33 UTC, gabe-l-hart requested changes
This overall looks really good Max! I went through the broad strokes of it and the overall refactor looks very solid. I took a much more thorough pass over `BaseBlock` and have a number of thoughts/suggestions there. A lot of them are somewhat nit-picky, but I think it's important that this kind of foundational base class be really tight and I know how much harder it is to fix that tightness after-the-fact!

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        kwarg_fields = []
```suggestion
    arg_fields = arg_fields or []
    kwarg_fields = or kwarg_fields or []
```

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        raise ValueError(f"Unexpected input type: {type(inp)}")
Two things that I think would be cleaner here:

1. It looks like the body of the `if` and `elif` clauses are the same, so they can be collapsed
2. This should use the more idiomatic `isinstance(x, types)` type checking so that subclasses are respected

```suggestion
    if isinstance(inp, (dict, pd.DataFrame, Dataset):
        args = [inp.get(arg) for arg in arg_fields]
        kwargs = {kwarg: inp.get(kwarg) for kwarg in kwarg_fields}
    else:
        raise ValueError(f"Unexpected input type: {type(inp)}")
```

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +    pass
These look like they're not doing anything. I could see there being value in them for type checks later on (e.g. `if not isinstance(generator, BaseGeneratorBlock): ...`, but if that's the case, I'd like a nice docstring explaining why these are needed since they just look like extra indirection.

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        result_field: Optional[str] = None,
I'm still a bit confused/concerned about these as fields in the `generate` function. I'd like to get a detailed docstring about how these fields are used. Without reading deeper, I would think that this is an awkward way of doing `*args, **kwargs`. After deeper reading, it makes sense that these are field names that will be extracted from the `inputs`, but that's not clear to me from the names.

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +BLOCK_INPUT_TYPE = Union[Iterable[BLOCK_ROW_TYPE], pd.DataFrame, Dataset]
It may be worth naming this something that's more descriptive of what it is versus how it's used. Something like `DATASET_TYPE`. I think this would help readers of the class understand that a `Block` is supposed to operator on an abstract notion of a `DATASET` (iterable of rows with named columns).

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        if type(arg_fields) == str:
In general, any place you have `if type(x) == y`, it should be `if isinstance(x, y)`. The only reason to do it like you have here is to explicitly disallow derived subclasses from passing the check, and if you're intentionally going for that, you should use `is` instead of `==` to do an exact object equivalence on the type itself.

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        # minor type checking
These type coercions violate the type hints in the function signature. Either the types in the signature should explicitly allow these degenerate cases where a single instance gets converted to a list of size 1, or these should simply do type assertions.

I've personally fallen into this trap a TON: you want to make things as friendly as possible to your users and try to let the user do what feels natural. The problem with this kind of "help the user out" code is that it ultimately results in "magic" which only you know about and prevents users from being able to cleanly operate in the codebase as a self-service experience. My suggestion here is to be explicit about where/how you're helping the user out by guiding them with the type hints OR keep the signature simple and just make the user do the list wrapping.

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +            ), "Cannot have multiple 'result' fields for {name}"
This assertion error is a bit confusing to me since it's not actually interpolating the `{name}` field.

Also, one thing to think about (outside the scope of this PR): If this library evolves into strong foundation of abstractions, it will be important to think through how error semantics work. In particular, usage of `assert` should generally be reserved for programming errors. I think this case is exactly the case where a developer wrote the wrong code by sending in a `list` where a `str` is expected, but if we run into a situation where the user providing the args may be something that arrived via a service API call, we need to be able to capture 400-class vs 500-class errors (probably by raising some kind of appropriate exception).

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        result_field: Optional[str] = None,
Reading further, it seems like the `arg_fields`/`kwarg_fields`/`result_field` are essentially overrides on the pointers given to the `Block` at construction time. I would suggest that we _not_ allow this per-invocation override unless there's a strong reason to do so. My thinking is that a given instance of a `block` will be instantiated for exactly one usage, and the type + schema of the `inputs` should remain consistent through the lifecycle of that instance. If these block instances were eventually going to sit behind a service and be long-lived, I could see the argument for allowing the user to pass pointer overrides with each invocation, but it's always easier to add that functionality later than take it away later if having them becomes too confusing.

Also, if we _do_ keep these fields, I would suggest that we intentionally make them kwarg-only arguments so that it's clear a user must be very explicit about passing them. With that in hand, see my revised suggestion for this signature below:

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +def get_args_kwargs(
Since this is going to be a critical function for the operation of blocks, I have two thoughts:

1. It definitely needs a docstring explaining what it does
2. It would probably be cleaner as a `@staticmethod` on `BlockBase` to make it clear that it's attached to the operation of a block

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        inp[result_field] = res
```suggestion
    if isinstance(inp, (dict, pd.DataFrame, Dataset):
        inp[result_field] = res
```

2024-07-10 13:33 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +def write_result(
Same comment here about making this a `@staticmethod` on `BlockBase`. It may also be worth making it an instance method and making `result_field` `Optional` to fall back to `self.result_field`

2024-07-10 13:55 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        raise ValueError(f"Unexpected input type: {type(inp)}")
Ah, yes good catch, I had initially put that second elif statement in there as a placeholder. But now revisiting it, I suspect we'll just handle it in the same way as the if statement, so collapsing the two is good

2024-07-10 13:58 UTC, mvcrouse commented on fms_dgt/base/block.py
> +    pass
Yeah, my main thought was for type checking, but if we don't have an immediate use case for it, should we just scrap these two classes?

2024-07-10 14:01 UTC, mvcrouse commented on fms_dgt/base/block.py
> +def write_result(
Ah, yes that was actually my original design, however I was trying to go the free-function route you had mentioned earlier. It was a bit simpler when it was an instance method, as we didn't have to pass the odd `result_field or self._result_field` as input, perhaps I'll put it back to that?

2024-07-10 14:03 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        # minor type checking
yep, that's a good point, I'll just do type assertions here

2024-07-10 14:18 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +def write_result(
Yeah, the free-function suggestion was certainly just a thought exercise. I think for these things member/static-member functions are probably good since the type in question is explicitly bound to the base class

2024-07-10 15:04 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        result_field: Optional[str] = None,
Since we execute a data builder on all tasks in parallel, we do have some cases where different tasks will have different inputs (usually different kwargs since some tasks ). But yes, definitely agree on having them be optional kwarg arguments

2024-07-10 16:13 UTC, gabe-l-hart requested changes
A couple more NITs/tightenings in the block base

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +            raise TypeError(f"arg_fields must be of type 'list'")
NIT: No need for the `f"` f-string prefix since there's no interpolation

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        result_field: str = None,
```suggestion
        result_field: Optional[str] = None,
```

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        res: Any,
Question on the use of `Any` here: Are there any type restrictions we need to make on the values that go into the dataset type fields?

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +DATASET_ROW_TYPE = Union[Dict, pd.Series]
Related to the question below, I think the `Dict` here could be further restricted as `Dict[str, _something_]`. If there are any restrictions on the types for the value, that `_something_` could be itself a big `Union` or type def, or it could just be `Any`.

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        return args, kwargs
Total code golf NIT, but...

```suggestion
        if isinstance(inp, (dict, pd.DataFrame, Dataset)):
            return (
                [inp.get(arg) for arg in arg_fields],
                {kwarg: inp.get(kwarg) for kwarg in kwarg_fields}
            )
        raise TypeError(f"Unexpected input type: {type(inp)}")

```

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +            raise TypeError(f"Unexpected input type: {type(inp)}")
Similar NIT:

```suggestion
        raise TypeError(f"Unexpected input type: {type(inp)}")
```

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        arg_fields: Optional[List[str]] = None,
This should have the `*` in there to force kwargs on the `_fields`

2024-07-10 16:13 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        raise NotImplementedError
```suggestion
    @abstractmethod
    def _validate(self, *args: Any, **kwargs: Any) -> bool:
        """Derived validators must implement _validate with their core logic"""
```

2024-07-10 16:20 UTC, mvcrouse commented on fms_dgt/base/block.py
> +            raise TypeError(f"arg_fields must be of type 'list'")
Ha, yes good catch

2024-07-10 16:23 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        res: Any,
My suspicion is that the result will always be a basic data type, e.g., float, bool, str, etc., but I'm not sure. In particular, once generators start pulling information from, say, knowledge graphs or generators, data types may get to be more elaborate

2024-07-10 16:24 UTC, mvcrouse commented on fms_dgt/base/block.py
> +DATASET_ROW_TYPE = Union[Dict, pd.Series]
I'll go with Dict[str, Any]. I frequently pass a dictionary with the SDG object I'm building up as one of the values

2024-07-10 16:24 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        return args, kwargs
ha, love it

2024-07-10 16:25 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        arg_fields: Optional[List[str]] = None,
Ahh yes good catch

2024-07-10 18:40 UTC, yuanchi2807 commented
Hi @mvcrouse and all, 

I am going through a mental exercise how a module from DPK, say [code quality assessment](https://github.com/IBM/data-prep-kit/blob/dev/transforms/code/code_quality/python/src/code_quality_transform.py#L189) or [language identification](https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/lang_id/python/src/lang_id_transform.py#L43), may be enabled as a Block or ValidatorBlock. 

In DPK we standardize module IO data format to be pyarrow tables, which may be mapped to other iterable BLOCK_ROW_TYPE. For ValidatorBlocks, what can I reuse from the base class?

2024-07-10 19:37 UTC, mvcrouse commented
> Hi @mvcrouse and all,
> 
> I am going through a mental exercise how a module from DPK, say [code quality assessment](https://github.com/IBM/data-prep-kit/blob/dev/transforms/code/code_quality/python/src/code_quality_transform.py#L189) or [language identification](https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/lang_id/python/src/lang_id_transform.py#L43), may be enabled as a Block or ValidatorBlock.
> 
> In DPK we standardize module IO data format to be pyarrow tables, which may be mapped to other iterable BLOCK_ROW_TYPE. For ValidatorBlocks, what can I reuse from the base class?

For a ValidatorBlock, the way we had been using it is to have a `generate` method [(see here)](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/fms_dgt/base/block.py#L127) and a `_validate` method [(see here)](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/fms_dgt/base/block.py#L145). The generate contains whatever bulk processing steps are required, then calls _validate method on each input to give it either a true or a false. When I was doing some minor testing with IL, I just called their blocks from our blocks [(see here)](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/tests/compatibility_tests/blocks.py#L15). I imagine a DPK transform would be similar?

2024-07-10 20:28 UTC, gabe-l-hart reviewed
Super close on the block base stuff! A couple more comments

2024-07-10 20:28 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        if not (isinstance(arg_fields, list) or arg_fields is None):
Hm. I'm confused why we have `None` as a default (sidebar: if `None` is _valid_, the type hint needs to be `Optional[List[str]]`), but then we immediately raise if it's set to `None`.

2024-07-10 20:28 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        res: Any,
Makes sense. I was more curious if we needed to place any restrictions there to allow for serailizability, but I think `Any` is fine for now.

2024-07-10 20:28 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +    pass
I still think we need to reach a conclusion here. If we keep them, they need docstrings explaining why they're here

2024-07-10 20:55 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        if not (isinstance(arg_fields, list) or arg_fields is None):
My thought was that `None` would be the default when the data builder configs excluded those fields, and when that would happen we'd have the `arg_fields`, `kwarg_fields`, `result_field` set only in code (like we use in the API-task databuilder [here](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/fms_dgt/databuilders/api/generate.py#L56) and [here](https://github.com/mvcrouse/fms-sdg/blob/block_design/fms_dgt/databuilders/api/api_function_checking.yaml). I'd tend to want to keep these optional to have less things be forced into the configs. For me, it's been clearer to have the strings defined for those fields in the same file that they are later used, e.g., [here](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/fms_dgt/databuilders/api/generate.py#L64) we define what the result field is and [here](https://github.com/mvcrouse/fms-sdg/blob/6f5631ad361106cdcf64ec5f41d842361d67a0d6/fms_dgt/databuilders/api/generate.py#L93) we use that string, so it feels less like a magic string. Though I'm not strongly opposed to the alternative if there's a case for these being required in the config

2024-07-10 20:56 UTC, mvcrouse commented on fms_dgt/base/block.py
> +    pass
I think it's better we just drop them, to be honest. We don't have any type-checking considerations right now, and directory structure provides an equivalent amount of block-categorization when someone is trying to understand the code

2024-07-10 21:05 UTC, yuanchi2807 commented
> For a ValidatorBlock, the way we had been using it is to have a `generate` method

Could `generate` method be kept in GeneratorBlock and `validate` method be kept within the ValidatorBlock? One generated batch may be fed to multiple Validators? Is that a valid use case?

2024-07-10 22:11 UTC, mvcrouse commented
> > For a ValidatorBlock, the way we had been using it is to have a `generate` method
> 
> Could `generate` method be kept in GeneratorBlock and `validate` method be kept within the ValidatorBlock? One generated batch may be fed to multiple Validators? Is that a valid use case?

Currently we only use `generate` as a way of keeping some notion of API-surface compatibility with IL, rather than using that name to reflect what's really going on within the block. Previously we had all blocks implement a more generically-named `__call__` function which contained their core logic. All of this to say, we'll probably keep `generate` for now for all blocks to keep that compatibility, with the understanding that it's a bit of a confusingly named method

2024-07-11 13:21 UTC, hickeyma requested changes
Thanks @mvcrouse for the work on this. I like the general direction

If we are trying to be near to the InstructLab API for integration purposes then I have the following suggestions:

1. Should `databuilder` be renamed as `pipeline`? See https://github.com/instructlab/sdg/blob/main/src/instructlab/sdg/pipeline.py
2. Should the databuilder/pipeline configuration be nearer to InstructLab configuration. For example `simple` databuilder config would become something like this:

```yaml
version: "1.0"
name: simple
blocks:
  - name: gen_questions
    type: genai
    config:
      arg_fields:
      - prompt
    kwarg_fields:
      - stop_sequences
    result_field: output
    temperature: 0.0
    max_new_tokens: 512
    min_new_tokens: 1
    model_id_or_path: mistralai/mixtral-8x7b-instruct-v01
  - name: validate_answers
    type: rouge_scorer
    config:
      arg_fields:
      - new_toks
      - all_toks
    result_field: output
    filter: true
    threshold: 1.0
```

2024-07-11 13:28 UTC, mvcrouse commented
> Thanks @mvcrouse for the work on this. I like the general direction
> 
> If we are trying to be near to the InstructLab API for integration purposes then I have the following suggestions:
> 
> 1. Should `databuilder` be renamed as `pipeline`? See https://github.com/instructlab/sdg/blob/main/src/instructlab/sdg/pipeline.py
> 2. Should the databuilder/pipeline configuration be nearer to InstructLab configuration. For example `simple` databuilder config would become something like this:
> 
> ```yaml
> version: "1.0"
> name: simple
> blocks:
>   - name: gen_questions
>     type: genai

I think we'll want to maintain a distinction between `databuilder` and `pipeline`, as one is more for code-based SDG and the other is config-based. However, I do think one of the next additions should be to add a `pipeline` class in. On point (2), I'm not opposed to that, it seems the change would just be having a `name` field and then treating `blocks` as a list?

2024-07-11 14:20 UTC, hickeyma commented
> I think we'll want to maintain a distinction between databuilder and pipeline, as one is more for code-based SDG and the other is config-based. However, I do think one of the next additions should be to add a pipeline class in. On point (2), I'm not opposed to that, it seems the change would just be having a name field and then treating blocks as a list?

I am thinking the `pipeline` is just the flow of a request that is processed by blocks. If this is the case, is `Block` the extension where you add new types with logic in code?

2024-07-11 14:31 UTC, mvcrouse commented
> > I think we'll want to maintain a distinction between databuilder and pipeline, as one is more for code-based SDG and the other is config-based. However, I do think one of the next additions should be to add a pipeline class in. On point (2), I'm not opposed to that, it seems the change would just be having a name field and then treating blocks as a list?
> 
> I am thinking the `pipeline` is just the flow of a request that is processed by blocks. If this is the case, is `Block` the extension where you add new types with logic in code?

Ah so I'm viewing a `pipeline` as a direct chain of blocks, where the output of one block is directly piped into the input of another block. That's more so how they do it in IL, right?

2024-07-11 15:16 UTC, mvcrouse commented
> > Ah so I'm viewing a pipeline as a direct chain of blocks, where the output of one block is directly piped into the input of another block. That's more so how they do it in IL, right?
> 
> That is what I am thinking especially the direction being proposed in the following design docs: [instructlab/dev-docs#109](https://github.com/instructlab/dev-docs/pull/109) and [instructlab/dev-docs#113](https://github.com/instructlab/dev-docs/pull/113)

Gotcha, then I think I'd rather `pipeline` be its own separate class and keep `data builders` as they are, that way we can have both code-based frameworks and config-based

2024-07-11 16:15 UTC, gabe-l-hart approved these changes
All of my comments have been addressed at this point. I was misreading the type checking logic and have one small suggestion to make it easier to read, but otherwise it looks good to go to me!

2024-07-11 16:15 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        if not (isinstance(arg_fields, list) or arg_fields is None):
🤦 I was reading the parens wrong. I thought this was raising if it IS `None`, not if it's not. I think this could be simplified to `if not isinstance(arg_fields, (list, type(None)))` which would be a little simpler to read

2024-07-11 16:51 UTC, hickeyma approved these changes
I am happy with direction of the block design for now. The follow on PR should be around:

1. How we deal with the pipeline or workflow of blocks 
2. How developer add custom data generation

2024-07-11 16:55 UTC, mvcrouse commented
> I am happy with direction of the block design for now. The follow on PR should be around:
> 
> 1. How we deal with the pipeline or workflow of blocks
> 2. How developer add custom data generation

Yep, totally agree

2024-07-11 16:57 UTC, merged