Pipeline
foundation-model-stack/fms-dgt pull request #47
Opened 2024-07-31 14:41 UTC by mvcrouse

## What this PR does / why we need it

This PR introduces the `Pipeline` object, which is a purely config-based SDG pipeline that consists of a list of blocks chained together.

## Special notes for your reviewer

There are three main files to look at:
1. pipeline.py (main pipeline object, inherits from Databuilder to maintain input/output and tasks functionality)
2. registry.py (I added a dynamic import system to help mitigate dependency I was starting to see with users, however, this could be bad practice...)
3. blockchain.py (first instance of compositional blocks)

## If applicable**
- [X] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

2024-07-31 14:45 UTC, gabe-l-hart commented
@mvcrouse looks like you need to rebase with signoff:

```sh
# NOTE: "origin" is the central repo not the fork here, so swap as needed
git fetch origin main
git rebase origin/main --signoff
git push -f
```

2024-07-31 15:06 UTC, mvcrouse commented
> @mvcrouse looks like you need to rebase with signoff:
> 
> ```shell
> # NOTE: "origin" is the central repo not the fork here, so swap as needed
> git fetch origin main
> git rebase origin/main --signoff
> git push -f
> ```

Ahh yes,

2024-08-01 21:47 UTC, gabe-l-hart requested changes
A bunch of little NITs around dynamic logging and a few spots of code golf. The overall architecture looks great. I do think we should rename `BlockChain` to avoid confusion and/or "nefarious code sniffers" from pinging with false-positives.

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        type: str = None,
I'm always wary of using the name `type` for a variable since it's such a fundamental python primitive. Not a strong objection, but it always catches my eye. Same thing for `id`.

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/databuilder.py
> +        if isinstance(config, DataBuilderConfig):
Do we need to expand the type hint for `config` based on this?

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +            example = next(self._dataloader)
Do you need to rewind after `next`? It probably depends on the nature of `self._dataloader`, but I suspect if it's an `iterator`, calling this will mean that the first element is then not yielded in further iteration.

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +    """A data builder represents a means of constructing data for a set of tasks"""
NIT: copy-pasta docstring

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +        """ """
NIT: Should be a real docstring or be omitted

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +        )
🏌️ 
```suggestion
        config: PipelineConfig = PipelineConfig(**(config or {}))
```

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/compositions/chain.py
> +class BlockChain(BaseBlock):
Total naming NIT, but I'd be wary of calling this a `BlockChain` since it's not a [Blockchain](https://en.wikipedia.org/wiki/Blockchain). Maybe `BlockSequence`?

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +            sdg_logger.info(f"Running task: {task.name}")
Lazy logging:

```suggestion
            sdg_logger.info("Running task: %s", task.name)
```

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +    def _init_blocks(self):
This is pretty nuanced. I had missed that `_init_blocks` is the main logic in `DataBuilder`, so by overriding this, you're making this `DataBuilder` behave completely differently! A couple of thoughts/suggestions:

* In `DataBuilder`, it would be nice to have a docstring explaining that this method is _designed_ to be overloaded by derived classes.
* Here, it would be good to add a note above the call to `super().__init__` that mentions the fact that it will call `_init_blocks` and therefore initialize `self._pipeline`.

I went down this investigation because I got to `__call__` and saw `self._pipeline` which was not initialized anywhere in `__init__` and got worried!

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/compositions/chain.py
> +        if block_list is None:
Why have a default value of `None` then? I think it's better to just let the standard python semantics for a required argument stand. Also, the type hint is not `Optional`, so if you remove the default value, I don't think you need this check at all. If someone passes `None` to the value of an argument that type hints itself as something NOT `None`, that's their problem!

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/compositions/chain.py
> +                )
```suggestion
                sdg_logger.warn(
                    "Attribute '%s' is set but it will not be used in block '%s'"
                    attr,
                    self.name,
                )
```

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/compositions/chain.py
> +        for attr in ["arg_fields", "kwarg_fields", "result_field"]:
Where do these args come from? If these are standard block args, it would probably be best to put them in a `constants.py` module with good commands about what they do. Alternately, you could make them class-members of the `BaseBlock` class.

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/compositions/chain.py
> +            sdg_logger.info(f"Running block {block.name}")
```suggestion
            sdg_logger.info("Running block %s", block.name)
```

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/generators/llm.py
> +from fms_dgt.blocks import TYPE_KEY
Is this not used?

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/utilities/prompt_builder.py
> +            prompt = self._prompt + ""
Why add an empty string like this? Is it just to get a copy?

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/blocks/utilities/prompt_builder.py
> +                prompt = prompt.replace("{{" + k + "}}", v)
This looks like you're building a basic version of a template expander. I know other tools use fully-fledged template engines. Do you see the need for this eventually? As written it would not allow spacing between the braces and key which I know is allowed in `jinja2` (which also uses `{{ KEY }}` syntax), so I suspect you could end up with strange bugs here.

2024-08-01 21:47 UTC, gabe-l-hart commented on tests/blocks/generators/test_llm.py
> +    "type": "genai",
I suppose it's nicer to have the field be `"type"`, so I'm ok using that as the variable name

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/registry.py
> +                    f"Attempting dynamic import of {import_path} for {class_name}"
```suggestion
                    "Attempting dynamic import of %s for %s", import_path, class_name
```

2024-08-01 21:47 UTC, gabe-l-hart commented on fms_dgt/base/registry.py
> +                # we try both, but we will overwrite with include path
I'm not really following the logic of this conditional. Is this because it's used below and then there's a follow-on `try/except`? I think it would be cleanest to have a single function that handles the error handling and documents the error semantics under which it will raise carefully.

2024-08-01 22:27 UTC, mvcrouse commented on fms_dgt/blocks/utilities/prompt_builder.py
> +            prompt = self._prompt + ""
Yep that was the reason

2024-08-01 22:28 UTC, mvcrouse commented on fms_dgt/base/block.py
> +        type: str = None,
Same, I had gone back and forth on that, but it was nice to have `type` used in the block yaml config. However, internally it's immediately assigned to `_block_type` to not go any further

2024-08-01 22:28 UTC, mvcrouse commented on fms_dgt/base/databuilder.py
> +        if isinstance(config, DataBuilderConfig):
Hmm, yes, good point

2024-08-01 22:38 UTC, mvcrouse commented on fms_dgt/base/pipeline.py
> +            example = next(self._dataloader)
I had left that up to the implementation of the dataloader [(this is the default one, which restarts after it runs through the whole list)](https://github.com/foundation-model-stack/fms-dgt/blob/87bdb788bf20d9f789b5829aef4ce5c4fbc4c4b5/fms_dgt/dataloaders/default.py#L22). My thought was that there should be a clear signal as to when the set of initial examples had been completely used up (if someone is transforming a dataset with this, they don't want to transform an example multiple times)

2024-08-01 22:39 UTC, mvcrouse commented on fms_dgt/base/pipeline.py
> +    """A data builder represents a means of constructing data for a set of tasks"""
Ahh... there shall be a lot of those, I fear...

2024-08-01 22:53 UTC, mvcrouse commented on fms_dgt/base/pipeline.py
> +    def _init_blocks(self):
Ahh, yes very good point, I'll add both of these

2024-08-01 23:06 UTC, mvcrouse commented on fms_dgt/base/registry.py
> +                # we try both, but we will overwrite with include path
If, within an imported module, you have a module that hasn't been installed then you would get a ModuleNotFoundError. So here we attempt to distinguish between when `import_path` doesn't exist and when a module within `import_path` doesn't exist

2024-08-02 13:58 UTC, mvcrouse commented on fms_dgt/blocks/utilities/prompt_builder.py
> +                prompt = prompt.replace("{{" + k + "}}", v)
Yeah, we'd probably want jinja2 or other more built out libraries. This was more of a proof-of-concept to have an example working end-to-end with a pipeline

2024-08-02 14:41 UTC, sivasankalpp commented on tests/blocks/compositions/blockchain.py
> +class TestBlockChain:
I guess we would want to rename this file and class also to blocksequence?

2024-08-02 14:55 UTC, mvcrouse commented on tests/blocks/compositions/blockchain.py
> +class TestBlockChain:
Yep, good point

2024-08-02 14:58 UTC, sivasankalpp approved these changes
Looks good! Great work :) 

Running this command works perfectly! 
```command
fms_dgt --data-paths data/pipeline
```

2024-08-02 15:24 UTC, gabe-l-hart commented on fms_dgt/blocks/utilities/prompt_builder.py
> +                prompt = prompt.replace("{{" + k + "}}", v)
Yep, agreed. If we're aiming to match other APIs, I think `jinja2` is the standard

2024-08-02 17:42 UTC, gabe-l-hart commented on fms_dgt/base/block.py
> +        type: str = None,
Given that this is yanked from `yaml`, I like keeping it as is

2024-08-02 17:42 UTC, gabe-l-hart commented on fms_dgt/base/pipeline.py
> +            example = next(self._dataloader)
Ah, makes sense. It may be worth leaving a comment about this indicating that Dataloaders will have custom iteration semantics.

2024-08-02 17:53 UTC, gabe-l-hart requested changes
One last tiny NIT bout the unnecessary `+ ""` for string copy. Otherwise, it's ready to go.

2024-08-02 17:53 UTC, gabe-l-hart commented on fms_dgt/blocks/utilities/prompt_builder.py
> +            prompt = self._prompt + ""
Ok, I think you can safely remove this:

```py
>>> x = "test 1"
>>> y = x
>>> y = y.replace("1", "2")
>>> y
'test 2'
>>> x
'test 1'
```

2024-08-02 18:52 UTC, gabe-l-hart approved these changes
Ship it!

2024-08-02 18:57 UTC, merged